package com.jdpneto.stackengine

import java.awt.image.BufferedImage
import javax.imageio.ImageIO
import kotlin.math.sin
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

// ============================================================
// CROSS-PLATFORM CONTRACT (ported from GoldenCorpusTests.swift)
// ============================================================
// These goldens are the Android equivalence guardrail (spec §3, bible §18). The committed
// reference PNGs under src/test/resources/golden/ are the EXACT files generated by the Swift
// engine (copied from Packages/StackEngineCore/Tests/StackEngineCoreTests/Resources/golden/).
//
// There is deliberately NO regeneration path on Android: Kotlin must match the EXISTING PNGs —
// that equivalence is the whole point. When the pipeline changes intentionally, regenerate on the
// Swift side (SSS_REGENERATE_GOLDENS=1 swift test --filter GoldenCorpusTests -c release), commit
// the new PNGs there, and re-copy them here.
//
// The fixture generators (goldenBurst / goldenBrackets) are fully deterministic: seeded LCG only,
// no Date/SystemRandom, no platform-specific paths. The LCG uses Kotlin `UInt` arithmetic, which
// wraps mod 2^32 exactly like Swift's `&*`/`&+` on UInt32.
//
// Tolerances (minPSNR=45 dB, minSSIM=0.98, maxDeltaE=1.0) are loose enough for cross-platform
// Float accumulation drift and libm (sin/pow) last-ULP variance across platforms, yet tight
// enough to catch algorithm changes.
// ============================================================

// MARK: - Fixture generators

/**
 * A synthetic 96×64 Bayer burst — the cross-platform input contract for all four reducer looks.
 *
 * Scene: a linear ramp base (prevents constant-image degeneracy) with two sine octaves
 * (prevents aliasing into a flat field after stacking). All arithmetic is integer/Float with a
 * seeded LCG — no Date or SystemRandom so the output is bit-for-bit identical everywhere.
 *
 * Per-frame jitter (dx,dy) and CFA-mosaic sampling keep the fixture honest:
 *   • Translation jitter forces the aligner to do real work (a zero-offset burst collapses to
 *     a trivial identity alignment where any mistake is invisible).
 *   • RGGB mosaic + develop exercises the full ColorPipeline path, not just StackReducer.
 *
 * Layout (matches CFA contract in RawSensorFrame.kt):
 *   RGGB:  (even row, even col)=R, (even row, odd col)=G,
 *          (odd  row, even col)=G, (odd  row, odd  col)=B
 */
internal fun goldenBurst(): List<RawSensorFrame> {
    val W = 96; val H = 64
    val blackLevel = 64f; val whiteLevel = 1024f
    val piF = Math.PI.toFloat()   // Float.pi in Swift == 3.1415927f

    // Per-frame (dx, dy) integer translation jitter — kept small so the aligner doesn't saturate.
    // These are the cross-platform input: do NOT randomize them.
    val jitter: List<Pair<Int, Int>> = listOf(
        Pair(0, 0), Pair(1, 0), Pair(-1, 1), Pair(2, -1), Pair(0, 2), Pair(-2, 0)
    )
    check(jitter.size == 6) { "goldenBurst: expected 6 frames" }

    // LCG parameters (Numerical Recipes): multiplier=1664525, increment=1013904223, mod=2^32.
    // Seed is reset to the SAME value for each frame so noise is independent and reproducible.
    // Kotlin UInt ops wrap mod 2^32 — same semantics as Swift UInt32 &* / &+.
    val lcgMul: UInt = 1664525u
    val lcgInc: UInt = 1013904223u

    val frames = ArrayList<RawSensorFrame>(6)

    for ((frameIdx, jit) in jitter.withIndex()) {
        val (dx, dy) = jit
        // Unique per-frame seed (based on frame index) so noise patterns differ across frames.
        var seed: UInt = (42 + frameIdx * 7919).toUInt()

        val mosaic = ShortArray(W * H)

        for (row in 0 until H) {
            for (col in 0 until W) {
                // Sample from the scene using this frame's translation offset.
                // Clamp to valid range so edge frames don't wrap.
                val sx = (col - dx).coerceIn(0, W - 1)
                val sy = (row - dy).coerceIn(0, H - 1)

                val fx = sx.toFloat() / (W - 1).toFloat()   // ∈ [0,1]
                val fy = sy.toFloat() / (H - 1).toFloat()   // ∈ [0,1]

                // Scene: ramp + two sine octaves.  All channels receive the same luma
                // (neutral scene) — the CFA pattern provides the R/G/B split.
                val scene: Float = 0.3f +
                    0.4f * fx +                                                // ramp
                    0.15f * sin(piF * 4f * fx) * sin(piF * 3f * fy) +          // octave 1
                    0.08f * sin(piF * 9f * fx) * sin(piF * 7f * fy)            // octave 2

                // Noise amplitude ±8 on the [200,800] sensor range.
                seed = seed * lcgMul + lcgInc
                val noise = (((seed shr 16) and 0x7FFFu).toFloat() / 32767.0f - 0.5f) * 16.0f   // ±8

                // Map [0,1] scene to sensor range [200, 800] + noise.
                val raw = scene * 600.0f + 200.0f + noise
                val clamped = maxOf(0f, minOf(65535f, raw))      // Float(UInt16.max) = 65535
                mosaic[row * W + col] = clamped.toInt().toShort() // truncates toward zero like UInt16(Float)
            }
        }

        frames.add(RawSensorFrame(
            width = W, height = H,
            mosaic = mosaic,
            blackLevel = blackLevel, whiteLevel = whiteLevel,
            cfa = CFAPattern.RGGB,
            wbGains = Vec3(1f, 1f, 1f),
            colorMatrix = RawSensorFrame.IDENTITY_3X3.copyOf()
        ))
    }
    return frames
}

/**
 * A synthetic 96×64 focus-bracket sequence for the depth-of-field golden.
 * Reuses the existing [chainBracketFrames] fixture (defined in AffineAlignerChainTests.kt)
 * with two small similarity steps — translation-dominant, inside ChainBounds, deterministic.
 */
internal fun goldenBrackets(): List<PixelImage> {
    val steps = listOf(
        Transform2D.similarity(scale = 1.005f, rotation = 0.002f, tx = 0.8f, ty = -0.4f),
        Transform2D.similarity(scale = 1.004f, rotation = -0.001f, tx = -0.6f, ty = 0.5f),
    )
    return chainBracketFrames(w = 96, h = 64, steps = steps).first
}

// MARK: - GoldenCorpusTests

/**
 * Always-on golden regression suite for every look's full-pipeline output.
 *
 * Five cases (noiseReduction / smoothMotion / lightTrails / lowLightBoost / depth) each:
 *   1. Run the pipeline on a fully-deterministic synthetic input.
 *   2. Compare against the committed Swift-generated reference PNG (resources/golden/&lt;name&gt;.png).
 *   3. Assert PSNR ≥ 45 dB, SSIM ≥ 0.98, mean ΔE ≤ 1.0.
 *
 * These ARE the Android cross-platform equivalence acceptance gate (bible §18, spec §3):
 * a failure here means the Kotlin engine diverged from the iOS reference output. Debug the
 * divergence (Double promotion, copy semantics, edge handling, LCG wrap) — NEVER loosen the
 * tolerances.
 */
class GoldenCorpusTests {

    companion object {
        // The Android contract — pinned here, not buried in per-test magic numbers.
        private const val MIN_PSNR: Double = 45.0
        private const val MIN_SSIM: Double = 0.98
        private const val MAX_DELTA_E: Double = 1.0
    }

    // MARK: - Reducer looks (synthetic Bayer burst → Pipeline.reduce)

    @Test
    fun testGoldenNoiseReduction() {
        runGoldenTest("noiseReduction") {
            Pipeline.reduce(goldenBurst(), mode = StackMode.NOISE_REDUCTION, binnedDevelop = false)
        }
    }

    @Test
    fun testGoldenSmoothMotion() {
        runGoldenTest("smoothMotion") {
            Pipeline.reduce(goldenBurst(), mode = StackMode.SMOOTH_MOTION, binnedDevelop = false)
        }
    }

    @Test
    fun testGoldenLightTrails() {
        runGoldenTest("lightTrails") {
            Pipeline.reduce(goldenBurst(), mode = StackMode.LIGHT_TRAILS, binnedDevelop = false)
        }
    }

    @Test
    fun testGoldenLowLightBoost() {
        runGoldenTest("lowLightBoost") {
            Pipeline.reduce(goldenBurst(), mode = StackMode.LOW_LIGHT_BOOST, binnedDevelop = false)
        }
    }

    // MARK: - Depth-of-field look (synthetic brackets → FocusStacker)

    @Test
    fun testGoldenDepth() {
        val config = DepthConfig(workingResolution = null, maxFrames = 12)
        val result = assertNotNull(FocusStacker.allInFocus(goldenBrackets(), config),
                                   "FocusStacker.allInFocus returned null on goldenBrackets")
        runGoldenTest("depth") { result }
    }

    // MARK: - Core helper

    /**
     * Load a golden PNG from test resources and return:
     *   - A PixelImage decoded to linear-light (sRGB→linear via OutputTransform.decodeSRGB8)
     *   - The raw RGBA8 bytes (for PSNR comparison against another sRGB-encoded byte buffer)
     *
     * Channel-order contract: the Swift loader produces RGBA bytes with alpha=255 (the goldens are
     * fully opaque). javax.imageio decodes the PNG; `getRGB` yields packed ARGB ints which are
     * repacked here to the SAME R,G,B,A byte layout — alpha included so PSNR compares the full
     * 4-byte-per-pixel buffers exactly like the Swift contract pins.
     */
    private fun loadGoldenPNG(name: String): Pair<PixelImage, ByteArray> {
        val stream = javaClass.getResourceAsStream("/golden/$name.png")
            ?: fail("bundled golden $name.png missing — copy it from the Swift Resources/golden/ (no Android regeneration path)")
        val img: BufferedImage = stream.use { ImageIO.read(it) }
        val w = img.width; val h = img.height
        val rgba = ByteArray(w * h * 4)
        for (y in 0 until h) {
            for (x in 0 until w) {
                val argb = img.getRGB(x, y)   // packed ARGB, non-premultiplied sRGB
                val i = (y * w + x) * 4
                rgba[i]     = ((argb shr 16) and 0xFF).toByte()   // R
                rgba[i + 1] = ((argb shr 8) and 0xFF).toByte()    // G
                rgba[i + 2] = (argb and 0xFF).toByte()            // B
                rgba[i + 3] = ((argb ushr 24) and 0xFF).toByte()  // A (255 — goldens are opaque)
            }
        }
        return Pair(OutputTransform.decodeSRGB8(rgba, w, h), rgba)
    }

    /** Run one golden test: produce the result, load the bundled reference, compare PSNR/SSIM/ΔE. */
    private fun runGoldenTest(name: String, produce: () -> PixelImage) {
        val result = produce()
        val (goldenImage, goldenRGBA8) = loadGoldenPNG(name)

        assertTrue(result.width == goldenImage.width && result.height == goldenImage.height,
                   "$name: result ${result.width}×${result.height} != golden ${goldenImage.width}×${goldenImage.height}")

        // Encode the result through the same sRGB8 path used when the golden was generated.
        // This round-trip (linear → sRGB8 → linear) is the canonical comparison domain: it
        // eliminates sub-ULP float differences and matches what the PNG stores.
        val resultRGBA8 = OutputTransform.encodeSRGB8(result)
        val resultImage = OutputTransform.decodeSRGB8(resultRGBA8, result.width, result.height)

        // PSNR: compare sRGB8-encoded bytes (same layout as the PNG pixels, alpha included).
        val psnr = Metrics.psnr(resultRGBA8, goldenRGBA8)

        // SSIM and ΔE: compare in the round-tripped sRGB8-decoded linear domain so both images
        // have identical clipping (highlights above 1.0 are clipped to 1.0 in the PNG, and the
        // round-trip applies the same clamp to the result — avoids spurious failures when
        // lowLightBoost saturates highlights that the golden also stores as 1.0).
        val ssim = Metrics.ssim(resultImage, goldenImage)
        val deltaE = Metrics.meanDeltaE(resultImage, goldenImage)

        // Report the cross-platform drift numbers (they go in the PR body).
        println("[GoldenCorpusTests] $name: PSNR=${"%.2f".format(psnr)} dB  SSIM=${"%.6f".format(ssim)}  meanDeltaE=${"%.4f".format(deltaE)}")

        assertTrue(psnr >= MIN_PSNR,
            "$name: PSNR ${"%.1f".format(psnr)} dB < $MIN_PSNR dB threshold (Kotlin output drifted from the iOS golden)")
        assertTrue(ssim >= MIN_SSIM,
            "$name: SSIM ${"%.4f".format(ssim)} < $MIN_SSIM threshold")
        assertTrue(deltaE <= MAX_DELTA_E,
            "$name: mean ΔE76 ${"%.3f".format(deltaE)} > $MAX_DELTA_E threshold")
    }
}
