package com.jdpneto.stackengine

import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import org.junit.jupiter.api.Assumptions
import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import kotlin.test.fail

// ============================================================
// REAL-CAPTURE CROSS-PLATFORM CONTRACT (bible §18 tier: real device data)
// ============================================================
// Five RAW bursts captured on a Pixel 10 Pro (2026-06-11 device verification), developed to
// working-resolution frames (1020×768, JPEG q95) — EXACTLY the linear-light input the engine's
// align/stack stages see on device. One burst per look:
//
//   noiseReduction (8 frames) / smoothMotion (5) / lightTrails (10) / lowLightBoost (6)
//   depthOfField (5 — a near→far focus sweep through FocusStacker, not Pipeline.reduce)
//
// Each output is compared against ONE committed reference PNG shared by BOTH engines
// (resources/real-captures/refs/<look>.png — same bytes live in the Swift package's Resources).
// That makes this suite a cross-platform contract on REAL content: Pixel frames pushed through
// the Kotlin and Swift engines must both land within golden tolerances of the same reference.
//
// REGENERATION (refs are generated by THIS Kotlin suite — the inverse of the synthetic goldens,
// which are generated by Swift):
//
//   SSS_REGENERATE_REAL_CAPTURES=1 ./gradlew :stackengine:test --tests '*RealCapture*'
//
// writes the 5 PNGs to /tmp/sss-real-captures/ and then skips (no comparisons during
// regeneration so a stale ref can never self-bless). Copy them into BOTH resource trees
// (src/test/resources/real-captures/refs/ and the Swift Resources/real-captures/refs/),
// then re-run both suites without the variable.
//
// Tolerances are the EXACT golden-corpus gates (minPSNR=45 dB, minSSIM=0.98, maxDeltaE=1.0):
// loose enough for cross-platform Float drift and javax.imageio↔ImageIO JPEG-decode variance,
// tight enough to catch algorithm changes. NEVER loosen them — debug the divergence instead.
// ============================================================

/**
 * Real-Pixel-burst regression suite: every look's full align+stack output on genuine handheld
 * captures, gated against one committed cross-platform reference per look.
 */
class RealCaptureRegressionTests {

    companion object {
        // The contract — identical to GoldenCorpusTests; pinned here, never loosened.
        private const val MIN_PSNR: Double = 45.0
        private const val MIN_SSIM: Double = 0.98
        private const val MAX_DELTA_E: Double = 1.0

        private const val REGEN_DIR = "/tmp/sss-real-captures"
    }

    private val regenerating: Boolean
        get() = System.getenv("SSS_REGENERATE_REAL_CAPTURES") == "1"

    /**
     * Heavy by design (full CPU stacks on 1020×768 real frames): opt-in via env so the routine
     * `./gradlew test` loop stays fast. CI / pre-merge runs set the variable:
     * `SSS_REAL_CAPTURES=1 ./gradlew :stackengine:test --tests '*RealCapture*'`.
     * Regeneration (SSS_REGENERATE_REAL_CAPTURES=1) implies opt-in.
     */
    private fun requireOptIn() {
        Assumptions.assumeTrue(regenerating || System.getenv("SSS_REAL_CAPTURES") == "1",
            "heavy real-capture regression — run with SSS_REAL_CAPTURES=1")
    }

    // MARK: - Reducer looks (developed Pixel frames → Pipeline.reduceImages)

    @Test
    fun testRealCaptureNoiseReduction() {
        requireOptIn()
        runRealCaptureTest("noiseReduction", frameCount = 8) { frames ->
            // Frames are already at working resolution — no further downscale (workingResolution
            // = null), default searchRange: the exact parameters of the device batch path.
            Pipeline.reduceImages(frames, mode = StackMode.NOISE_REDUCTION)
        }
    }

    @Test
    fun testRealCaptureSmoothMotion() {
        requireOptIn()
        runRealCaptureTest("smoothMotion", frameCount = 5) { frames ->
            Pipeline.reduceImages(frames, mode = StackMode.SMOOTH_MOTION)
        }
    }

    @Test
    fun testRealCaptureLightTrails() {
        requireOptIn()
        runRealCaptureTest("lightTrails", frameCount = 10) { frames ->
            Pipeline.reduceImages(frames, mode = StackMode.LIGHT_TRAILS)
        }
    }

    @Test
    fun testRealCaptureLowLightBoost() {
        requireOptIn()
        runRealCaptureTest("lowLightBoost", frameCount = 6) { frames ->
            Pipeline.reduceImages(frames, mode = StackMode.LOW_LIGHT_BOOST)
        }
    }

    // MARK: - Depth-of-field look (focus sweep → FocusStacker)

    @Test
    fun testRealCaptureDepthOfField() {
        requireOptIn()
        runRealCaptureTest("depthOfField", frameCount = 5) { frames ->
            // Matches the device coordinator's call (StackCaptureCoordinator depth path):
            // frames already at/below the working-resolution preset so no engine downscale
            // (workingResolution = null — FocusStacker only halves when the source exceeds the
            // target, and 1020 px < the 1500 px preset), maxFrames = actual frame count,
            // chain alignment ON (the default — the handheld promise).
            FocusStacker.allInFocus(frames,
                config = DepthConfig(workingResolution = null, maxFrames = frames.size))
                ?: fail("FocusStacker.allInFocus returned null on the depthOfField sweep")
        }
    }

    // MARK: - Fixture loading

    /**
     * Decode a captured working-resolution JPEG to the linear-light PixelImage the engine's
     * align/stack stages consume on device: raw sRGB bytes → OutputTransform.decodeSRGB8.
     * (Unlike the depth-brackets loader, which deliberately skips linearization for its pinned
     * alignment numbers, this suite reproduces the production stacking input.)
     */
    private fun loadFrames(name: String, frameCount: Int): List<PixelImage> =
        (0 until frameCount).map { i ->
            val file = "frame-%02d.jpg".format(i)
            // A missing BUNDLED fixture is a build/resource misconfiguration, never a skip —
            // skipping here would silently disable the whole real-data suite.
            val stream = javaClass.getResourceAsStream("/real-captures/$name/$file")
                ?: fail("bundled capture $name/$file missing — check src/test/resources/real-captures/")
            val img: BufferedImage = stream.use { ImageIO.read(it) }
            val w = img.width; val h = img.height
            val rgba = ByteArray(w * h * 4)
            for (y in 0 until h) {
                for (x in 0 until w) {
                    val argb = img.getRGB(x, y)
                    val base = (y * w + x) * 4
                    rgba[base]     = ((argb shr 16) and 0xFF).toByte()   // R
                    rgba[base + 1] = ((argb shr 8) and 0xFF).toByte()    // G
                    rgba[base + 2] = (argb and 0xFF).toByte()            // B
                    rgba[base + 3] = ((argb ushr 24) and 0xFF).toByte()  // A (opaque)
                }
            }
            OutputTransform.decodeSRGB8(rgba, w, h)
        }

    /**
     * Load a committed reference PNG and return:
     *   - A PixelImage decoded to linear-light (sRGB→linear via OutputTransform.decodeSRGB8)
     *   - The raw RGBA8 bytes (for PSNR comparison against another sRGB-encoded byte buffer)
     * Same channel-order contract as GoldenCorpusTests.loadGoldenPNG.
     */
    private fun loadReferencePNG(name: String): Pair<PixelImage, ByteArray> {
        val stream = javaClass.getResourceAsStream("/real-captures/refs/$name.png")
            ?: fail("bundled reference $name.png missing — regenerate with SSS_REGENERATE_REAL_CAPTURES=1 and copy into resources/real-captures/refs/")
        val img: BufferedImage = stream.use { ImageIO.read(it) }
        val w = img.width; val h = img.height
        val rgba = ByteArray(w * h * 4)
        for (y in 0 until h) {
            for (x in 0 until w) {
                val argb = img.getRGB(x, y)
                val i = (y * w + x) * 4
                rgba[i]     = ((argb shr 16) and 0xFF).toByte()   // R
                rgba[i + 1] = ((argb shr 8) and 0xFF).toByte()    // G
                rgba[i + 2] = (argb and 0xFF).toByte()            // B
                rgba[i + 3] = ((argb ushr 24) and 0xFF).toByte()  // A (255 — refs are opaque)
            }
        }
        return Pair(OutputTransform.decodeSRGB8(rgba, w, h), rgba)
    }

    // MARK: - Core helper

    /**
     * Run one real-capture case: load the burst, produce the result, then either
     *   - regenerate: write `name.png` to /tmp/sss-real-captures/ and skip, or
     *   - compare against the committed shared reference with the golden gates.
     */
    private fun runRealCaptureTest(name: String, frameCount: Int,
                                   produce: (List<PixelImage>) -> PixelImage) {
        val frames = loadFrames(name, frameCount)
        val result = produce(frames)
        // Encode through the same sRGB8 path the refs were generated with — the round-trip
        // (linear → sRGB8 → linear) is the canonical comparison domain (matches the PNG storage
        // and applies identical highlight clipping to both sides).
        val resultRGBA8 = OutputTransform.encodeSRGB8(result)

        if (regenerating) {
            // Regeneration path — write the result, then skip (never compare against itself).
            val dir = File(REGEN_DIR).apply { mkdirs() }
            val out = BufferedImage(result.width, result.height, BufferedImage.TYPE_INT_ARGB)
            for (y in 0 until result.height) {
                for (x in 0 until result.width) {
                    val i = (y * result.width + x) * 4
                    val r = resultRGBA8[i].toInt() and 0xFF
                    val g = resultRGBA8[i + 1].toInt() and 0xFF
                    val b = resultRGBA8[i + 2].toInt() and 0xFF
                    val a = resultRGBA8[i + 3].toInt() and 0xFF
                    out.setRGB(x, y, (a shl 24) or (r shl 16) or (g shl 8) or b)
                }
            }
            val file = File(dir, "$name.png")
            ImageIO.write(out, "png", file)
            println("[RealCaptureRegressionTests] wrote ${file.absolutePath}")
            println("[RealCaptureRegressionTests] copy into BOTH: android/stackengine/src/test/resources/real-captures/refs/ and Packages/StackEngineCore/Tests/StackEngineCoreTests/Resources/real-captures/refs/")
            Assumptions.assumeTrue(false,
                "refs regenerated — copy into both resource trees and re-run without SSS_REGENERATE_REAL_CAPTURES")
            return
        }

        val (refImage, refRGBA8) = loadReferencePNG(name)
        assertTrue(result.width == refImage.width && result.height == refImage.height,
                   "$name: result ${result.width}×${result.height} != reference ${refImage.width}×${refImage.height}")

        // PSNR: compare sRGB8-encoded bytes (same layout as the PNG pixels, alpha included).
        val psnr = Metrics.psnr(resultRGBA8, refRGBA8)

        // SSIM and ΔE: compare in the round-tripped sRGB8-decoded linear domain so both images
        // carry identical clipping.
        val resultImage = OutputTransform.decodeSRGB8(resultRGBA8, result.width, result.height)
        val ssim = Metrics.ssim(resultImage, refImage)
        val deltaE = Metrics.meanDeltaE(resultImage, refImage)

        // Report the cross-platform drift numbers (they go in the PR body).
        println("[RealCaptureRegressionTests] $name: PSNR=${"%.2f".format(psnr)} dB  SSIM=${"%.6f".format(ssim)}  meanDeltaE=${"%.4f".format(deltaE)}")

        assertTrue(psnr >= MIN_PSNR,
            "$name: PSNR ${"%.1f".format(psnr)} dB < $MIN_PSNR dB threshold (output drifted from the shared real-capture reference)")
        assertTrue(ssim >= MIN_SSIM,
            "$name: SSIM ${"%.4f".format(ssim)} < $MIN_SSIM threshold")
        assertTrue(deltaE <= MAX_DELTA_E,
            "$name: mean ΔE76 ${"%.3f".format(deltaE)} > $MAX_DELTA_E threshold")
    }
}
