import XCTest
import simd
import ImageIO
import CoreGraphics
@testable import StackEngineCore

// ============================================================
// REAL-CAPTURE CROSS-PLATFORM CONTRACT (bible §18 tier: real device data)
// ============================================================
// Five RAW bursts captured on a Pixel 10 Pro (2026-06-11 device verification), developed to
// working-resolution frames (1020×768, JPEG q95) — EXACTLY the linear-light input the engine's
// align/stack stages see on device. One burst per look:
//
//   noiseReduction (8 frames) / smoothMotion (5) / lightTrails (10) / lowLightBoost (6)
//   depthOfField (5 — a near→far focus sweep through FocusStacker, not Pipeline.reduce)
//
// Each output is compared against ONE committed reference PNG shared by BOTH engines
// (Resources/real-captures/refs/<look>.png — same bytes live in the Android test resources).
// That makes this suite a cross-platform contract on REAL content: Pixel frames pushed through
// the Swift and Kotlin engines must both land within golden tolerances of the same reference.
//
// There is deliberately NO regeneration path on this side: the refs are generated by the KOTLIN
// suite (the inverse of the synthetic goldens, which Swift generates) —
//   SSS_REGENERATE_REAL_CAPTURES=1 ./gradlew :stackengine:test --tests '*RealCapture*'
// — then copied into BOTH resource trees. Swift must match the EXISTING PNGs; that equivalence
// is the whole point.
//
// Tolerances are the EXACT golden-corpus gates (minPSNR=45 dB, minSSIM=0.98, maxDeltaE=1.0):
// loose enough for cross-platform Float drift and ImageIO↔javax.imageio JPEG-decode variance,
// tight enough to catch algorithm changes. NEVER loosen them — debug the divergence instead.
// ============================================================

/// Real-Pixel-burst regression suite: every look's full align+stack output on genuine handheld
/// captures, gated against one committed cross-platform reference per look.
final class RealCaptureRegressionTests: XCTestCase {

    // The contract — identical to GoldenCorpusTests; pinned here, never loosened.
    private static let minPSNR:   Double = 45.0
    private static let minSSIM:   Double = 0.98
    private static let maxDeltaE: Double = 1.0

    /// Heavy by design (full CPU stacks on 1020×768 real frames): opt-in via env so the routine
    /// `swift test` loop stays fast. CI / pre-merge runs set the variable:
    /// `SSS_REAL_CAPTURES=1 swift test --filter RealCaptureRegressionTests` (use -c release).
    private func requireOptIn() throws {
        guard ProcessInfo.processInfo.environment["SSS_REAL_CAPTURES"] == "1" else {
            throw XCTSkip("heavy real-capture regression — run with SSS_REAL_CAPTURES=1 (use -c release)")
        }
    }

    // MARK: - Reducer looks (developed Pixel frames → Pipeline.reduceImages)

    func testRealCaptureNoiseReduction() throws {
        try requireOptIn()
        try runRealCaptureTest(name: "noiseReduction", frameCount: 8) { frames in
            // Frames are already at working resolution — no further downscale (workingResolution
            // = nil), default searchRange: the exact parameters of the device batch path.
            Pipeline.reduceImages(frames, mode: .noiseReduction)
        }
    }

    func testRealCaptureSmoothMotion() throws {
        try requireOptIn()
        try runRealCaptureTest(name: "smoothMotion", frameCount: 5) { frames in
            Pipeline.reduceImages(frames, mode: .smoothMotion)
        }
    }

    func testRealCaptureLightTrails() throws {
        try requireOptIn()
        try runRealCaptureTest(name: "lightTrails", frameCount: 10) { frames in
            Pipeline.reduceImages(frames, mode: .lightTrails)
        }
    }

    func testRealCaptureLowLightBoost() throws {
        try requireOptIn()
        try runRealCaptureTest(name: "lowLightBoost", frameCount: 6) { frames in
            Pipeline.reduceImages(frames, mode: .lowLightBoost)
        }
    }

    // MARK: - Depth-of-field look (focus sweep → FocusStacker)

    func testRealCaptureDepthOfField() throws {
        try requireOptIn()
        try runRealCaptureTest(name: "depthOfField", frameCount: 5) { frames in
            // Matches the device coordinator's call (StackCaptureCoordinator depth path):
            // frames already at/below the working-resolution preset so no engine downscale
            // (workingResolution = nil — FocusStacker only halves when the source exceeds the
            // target, and 1020 px < the 1500 px preset), maxFrames = actual frame count,
            // chain alignment ON (the default — the handheld promise).
            guard let out = FocusStacker.allInFocus(frames,
                config: DepthConfig(workingResolution: nil, maxFrames: frames.count)) else {
                XCTFail("FocusStacker.allInFocus returned nil on the depthOfField sweep")
                return frames[0]
            }
            return out
        }
    }

    // MARK: - Fixture loading

    private enum Err: Error { case load }

    /// Decode an image at `url` into raw RGBA8 bytes via the CGContext pattern shared with
    /// GoldenCorpusTests / DepthBracketRegressionTests (one canonical decode path).
    private static func loadRGBA8(url: URL) throws -> (rgba8: [UInt8], width: Int, height: Int) {
        guard let src = CGImageSourceCreateWithURL(url as CFURL, nil),
              let cg = CGImageSourceCreateImageAtIndex(src, 0, nil) else { throw Err.load }
        let w = cg.width, h = cg.height
        var buf = [UInt8](repeating: 0, count: w * h * 4)
        guard let ctx = CGContext(
            data: &buf,
            width: w, height: h,
            bitsPerComponent: 8, bytesPerRow: w * 4,
            space: CGColorSpaceCreateDeviceRGB(),
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { throw Err.load }
        ctx.draw(cg, in: CGRect(x: 0, y: 0, width: w, height: h))
        return (buf, w, h)
    }

    /// Decode a captured working-resolution JPEG to the linear-light PixelImage the engine's
    /// align/stack stages consume on device: sRGB bytes → OutputTransform.decodeSRGB8.
    /// (Unlike the depth-brackets loader, which deliberately skips linearization for its pinned
    /// alignment numbers, this suite reproduces the production stacking input.)
    private func loadFrames(name: String, frameCount: Int) throws -> [PixelImage] {
        try (0..<frameCount).map { i in
            let file = String(format: "frame-%02d", i)
            guard let url = Bundle.module.url(forResource: file, withExtension: "jpg",
                                              subdirectory: "Resources/real-captures/\(name)")
            else {
                // A missing BUNDLED fixture is a build/resource misconfiguration, never a skip —
                // skipping here would silently disable the whole real-data suite.
                XCTFail("bundled capture \(name)/\(file).jpg missing — check Package.swift resources")
                throw Err.load
            }
            let (rgba8, w, h) = try Self.loadRGBA8(url: url)
            return OutputTransform.decodeSRGB8(rgba8, width: w, height: h)
        }
    }

    /// Load the committed (Kotlin-generated) reference PNG: linear PixelImage + raw RGBA8 bytes.
    private func loadReferencePNG(name: String) throws -> (image: PixelImage, rgba8: [UInt8]) {
        guard let url = Bundle.module.url(forResource: name, withExtension: "png",
                                          subdirectory: "Resources/real-captures/refs") else {
            // Missing reference is a build/resource misconfiguration, not a skip.
            XCTFail("bundled reference \(name).png missing — regenerate on the Kotlin side (SSS_REGENERATE_REAL_CAPTURES=1) and copy into Resources/real-captures/refs/")
            throw Err.load
        }
        let (rgba8, w, h) = try Self.loadRGBA8(url: url)
        return (OutputTransform.decodeSRGB8(rgba8, width: w, height: h), rgba8)
    }

    // MARK: - Core helper

    /// Run one real-capture case: load the burst, produce the result, compare against the shared
    /// committed reference with the golden gates.
    private func runRealCaptureTest(name: String, frameCount: Int,
                                    produce: ([PixelImage]) -> PixelImage) throws {
        let frames = try loadFrames(name: name, frameCount: frameCount)
        let result = produce(frames)
        let (refImage, refRGBA8) = try loadReferencePNG(name: name)

        XCTAssertTrue(result.width == refImage.width && result.height == refImage.height,
                      "\(name): result \(result.width)×\(result.height) != reference \(refImage.width)×\(refImage.height)")

        // Encode through the same sRGB8 path the refs were generated with — the round-trip
        // (linear → sRGB8 → linear) is the canonical comparison domain (matches the PNG storage
        // and applies identical highlight clipping to both sides).
        let resultRGBA8 = OutputTransform.encodeSRGB8(result)
        let resultImage = OutputTransform.decodeSRGB8(resultRGBA8, width: result.width, height: result.height)

        // PSNR: compare sRGB8-encoded bytes (same layout as the PNG pixels, alpha included).
        let psnr = Metrics.psnr(resultRGBA8, refRGBA8)
        // SSIM and ΔE: compare in the round-tripped sRGB8-decoded linear domain so both images
        // carry identical clipping.
        let ssim = Metrics.ssim(resultImage, refImage)
        let deltaE = Metrics.meanDeltaE(resultImage, refImage)

        // Report the cross-platform drift numbers (they go in the PR body).
        print("[RealCaptureRegressionTests] \(name): PSNR=\(String(format: "%.2f", psnr)) dB  SSIM=\(String(format: "%.6f", ssim))  meanDeltaE=\(String(format: "%.4f", deltaE))")

        XCTAssertGreaterThanOrEqual(psnr, Self.minPSNR,
            "\(name): PSNR \(String(format: "%.1f", psnr)) dB < \(Self.minPSNR) dB threshold (output drifted from the shared real-capture reference)")
        XCTAssertGreaterThanOrEqual(ssim, Self.minSSIM,
            "\(name): SSIM \(String(format: "%.4f", ssim)) < \(Self.minSSIM) threshold")
        XCTAssertLessThanOrEqual(deltaE, Self.maxDeltaE,
            "\(name): mean ΔE76 \(String(format: "%.3f", deltaE)) > \(Self.maxDeltaE) threshold")
    }
}
